---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentsowji
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: front-end
        image: nginx
        ports:
        - containerPort: 80 
        resources: 
          requests:
            memory: "100M"
            cpu: "100m"
          limits:
            memory: "100M"
            cpu: "100m"
