apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    label: front-end-service
spec:
  type: NodePort
  matchLabels:
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083

