apiVersion: v1
kind: Pod
metadata:
  name: multi-pod2
spec:
  containers:
  - image: nginx
    name: jupiter
    env:
    - name: name
      type: planet
  - image: busybox
    name: europa
    command: ["sleep","4800"]
    env:
    - name: name
      type: moon
