---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
  namespace: sowji
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - image: redis:alpine
    name: redis1
    ports:
    - containerPort: 88
   
