apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec: 
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /pv/data-analytics
  

