apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sowji-deployment
  namespace: sowji
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sowji-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
