apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  namespace: sowji-namespace
spec:
  containers:
    - name: busybox-container
      image: busybox
      args:
       - sleep
       - "1000"
      ports:
        - containerPort: 88
