---
apiVersion: v1
kind: Pod
metadata:
  name: super-user-pod
  namespace: sowji
spec:
   containers:
   - command:
     - sleep
     - "4800"
     name: super-user-pod
     image: busybox:1.28
     securityContext:
       capabilities:
         add: ["SYS_TIME"]
